[package]
name = "netcdf-sys"
version = "0.2.2"
authors = [
    "Michael Hiley <mhiley@gmail.com>",
    "Magnus Ulimoen <magnusu@met.no>"
]
license = "MIT"
description = "FFI bindings to NetCDF"
repository = "https://github.com/georust/netcdf"
documentation = "https://docs.rs/netcdf"
keywords = ["netcdf", "hdf", "hdf5", "cdm", "ffi"]
edition = "2018"
links = "netcdf"
build = "build.rs"

[dependencies]
libz-sys = { version = "1.0.25", optional = true }
curl-sys = { version = "0.4.25", optional = true }
hdf5-sys = { version = "0.6.1", features = ["hl", "deprecated"] }

[dev-dependencies]
lazy_static = "1.4.0"

[build-dependencies]
cmake = "0.1.42"

[features]
default = ["libz"]
memio = []
static = ["libz-sys/static", "hdf5-sys/static"]
# TODO: Link static curl (but only when using "dap") "curl-sys/static-curl", "curl-sys/static-ssl"
libz = ["libz-sys"]
dap = ["curl-sys"]

[patch]
[patch.crates-io]
hdf5-sys = { git = "https://github.com/magnusuMET/hdf5-rust", branch = "feature/static_build" }
