[package]
name = "netcdf-sys"
version = "0.2.1"
authors = [
    "Michael Hiley <mhiley@gmail.com>",
    "Magnus Ulimoen <magnusu@met.no>"
]
license = "MIT"
description = "FFI bindings to NetCDF"
repository = "https://github.com/georust/netcdf"
documentation = "https://docs.rs/netcdf"
keywords = ["netcdf", "hdf", "hdf5", "cdm", "ffi"]
edition = "2018"
links = "netcdf"
build = "build.rs"
exclude = [
    "source/conda.recipe/**",
    "source/ctest_scripts/**",
    "source/dap4_test/**",
#   "source/docs/**",
    "source/debug/**",
    "source/examples/**",
    "source/h5test/**",
    "source/ncdump/**",
    "source/ncgen/**",
    "source/ncgen3/**",
    "source/nc_perf/**",
    "source/nctest/**",
    "source/nc_test/**",
#   "source/nc_test4/**",
    "source/NUG/**",
    "source/unit_test/**",
]

[dependencies]
libz-sys = { version = "1.0.25" }
curl-sys = { version = "0.4.25", optional = true }
hdf5-sys = { version = "0.6.0", features = ["hl", "deprecated", "zlib"] }
netcdf-src = { path = "../netcdf-src", version = "0.1.0", optional = true }

[dev-dependencies]
lazy_static = "1.4.0"

[features]
default = []
memio = []
static = ["libz-sys/static", "hdf5-sys/static", "netcdf-src"]
# TODO: Link static curl (but only when using "dap") "curl-sys/static-curl", "curl-sys/static-ssl"
dap = ["curl-sys"]
