[package]
name = "netcdf-sys"
version = "0.2.1"
authors = [
    "Michael Hiley <mhiley@gmail.com>",
    "Magnus Ulimoen <magnusu@met.no>"
]
license = "MIT"
description = "FFI bindings to NetCDF"
repository = "https://github.com/georust/netcdf"
documentation = "https://github.com/georust/netcdf"
keywords = ["netcdf", "hdf", "hdf5", "cdm", "ffi"]
edition = "2018"
links = "netcdf"
build = "build.rs"

[dependencies]
hdf5-sys = { git = "https://github.com/magnusuMET/hdf5-rust.git", branch = "feature/static_build", features = ["hl", "threadsafe", "deprecated"] }
libz-sys = { version = "1.0.25", optional = true }

[dev-dependencies]
lazy_static = "1.4.0"

[build-dependencies]
cmake = "0.1.42"

[features]
default = ["libz"]
memio = []
static = ["libz-sys/static", "hdf5-sys/static"]
libz = ["libz-sys"]
